name: Build Firmware for DOIT ESP32 DEVKIT V1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      # --- PERUBAHAN DI SINI ---
      # Upload ketiga file yang dibutuhkan untuk flashing
      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          # Nama artifact yang akan berisi semua file
          name: esp32-flash-files
          # Path ke 3 file yang akan di-upload
          path: |
            .pio/build/doit_esp32_devkit_v1/bootloader.bin
            .pio/build/doit_esp32_devkit_v1/partitions.bin
            .pio/build/doit_esp32_devkit_v1/firmware.bin
            
