name: Build ESP32 Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      # --- PERBAIKAN DI SINI ---
      - name: List Build Files
        run: ls -l .pio/build/esp32dev/

      # --- DAN PERBAIKAN DI SINI ---
      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-flash-files
          path: .pio/build/esp32dev/*.bin
